-- Generated by tools/derive_sungrow_ftw_observe.py.
-- Source: srcfl/ftw@699873db3e7abe81f76e8110d1cefa4a38ba6efb
-- Path: drivers/sungrow.lua
-- SHA-256: 466a5f8637e6756fc2e1af4197d4edc1845474231413c0016f0e5900acb7b7ac
-- The fingerprint and poll functions stay byte-for-byte equal to the FTW
-- legacy source. Init and lifecycle code remove every write path.

DRIVER = {
  host_api_min = 1,
  host_api_max = 1,
  id           = "sungrow",
  name         = "Sungrow observe-only pilot",
  manufacturer = "Sungrow",
  version      = "1.3.2",
  legacy_ids   = { "sungrow-shx" },
  protocols    = { "modbus" },
  capabilities = { "meter", "pv", "battery" },
  description  = "Sungrow SH-series telemetry via Modbus TCP.",
  homepage     = "https://en.sungrowpower.com",
  authors      = { "FTW contributors" },
  tested_models = { "SH5.0RT", "SH6.0RT", "SH8.0RT", "SH10RT" },
  verification_status = "experimental",
  verification_notes = "Observe only. Exact pilot model and firmware approval is required.",
  connection_defaults = {
    port    = 502,
    unit_id = 1,
  },
}

PROTOCOL = "modbus"

local APPROVED_MODEL_FIRMWARE_PROFILES = {}
local sn_read = false
local rated_ac_w = 0
local pv_curtail_method = "active_power"
local latest_non_export_w = 0

local function bit_is_set(value, bit)
    return math.floor(value / (2 ^ bit)) % 2 == 1
end

function driver_fingerprint()
    local ok, regs = pcall(host.modbus_read, 4999, 1, "input")
    if not ok or regs == nil or regs[1] == nil then
        return nil
    end
    local code = regs[1]
    if code == 0 or code == 0xFFFF then
        return nil -- empty / sentinel read — inconclusive
    end
    local hi = math.floor(code / 256)
    if hi == 0x0E or hi == 0x0D then
        return true, {
            make = "Sungrow",
            model = string.format("0x%04X", code),
            confidence = 0.9,
        }
    end
    return false -- responded, but not a Sungrow SH hybrid signature
end

function driver_init(config)
    config = config or {}
    local model = tostring(config.model or "")
    local firmware = tostring(config.firmware or "")
    if not APPROVED_MODEL_FIRMWARE_PROFILES[model .. "|" .. firmware] then
        error(
            "Sungrow observe-only profile is not approved for model '" ..
            model .. "' and firmware '" .. firmware .. "'"
        )
    end

    host.set_make("Sungrow")
    local ok, dev = pcall(host.modbus_read, 4999, 1, "input")
    if ok and dev then
        host.log("info", "Device type code: " .. tostring(dev[1]))
    end
    local ok_rated, rated = pcall(host.modbus_read, 5000, 1, "input")
    if ok_rated and rated and rated[1] and rated[1] > 0 then
        rated_ac_w = rated[1] * 0.1 * 1000
    end
    local ok_ems, ems = pcall(host.modbus_read, 13049, 3, "holding")
    if ok_ems and ems then
        host.log("info", "EMS state: mode=" .. tostring(ems[1])
            .. " cmd=0x" .. string.format("%04x", ems[2])
            .. " power=" .. tostring(ems[3]) .. "W")
    end
end

function driver_poll()
    -- Read serial number once
    if not sn_read then
        local ok, sn_regs = pcall(host.modbus_read, 4990, 10, "input")
        if ok and sn_regs then
            local sn = ""
            for i = 1, 10 do
                local hi = math.floor(sn_regs[i] / 256)
                local lo = sn_regs[i] % 256
                if hi > 32 and hi < 127 then sn = sn .. string.char(hi) end
                if lo > 32 and lo < 127 then sn = sn .. string.char(lo) end
            end
            if string.len(sn) > 0 then
                host.set_sn(sn)
                sn_read = true
            end
        end
    end

    -- Sungrow running state is documented register 13000 (host address
    -- 12999). Power-flow status is documented 13001 (host address 13000):
    -- bit 2 = discharging, bit 1 = charging. Keep both as diagnostics so a
    -- reachable-but-stopped inverter is no longer misreported as merely 0 W.
    local ok_running, running_regs = pcall(host.modbus_read, 12999, 1, "input")
    local running_state = 0
    if ok_running and running_regs then running_state = running_regs[1] end

    local ok_flow, flow_regs = pcall(host.modbus_read, 13000, 1, "input")
    local power_flow_status = 0
    if ok_flow and flow_regs then power_flow_status = flow_regs[1] end
    local is_discharging = (math.floor(power_flow_status / 4) % 2) == 1

    -- PV power: 5016-5017, U32 LE, watts
    -- Observed on at least one SH-series firmware: this register stays
    -- at 0 even while MPPT1/MPPT2 V×I clearly indicate generation. So we
    -- also read the MPPT voltage+current pairs separately and use their
    -- product as a fallback when the top-level register doesn't match.
    local ok_pv, pv_regs = pcall(host.modbus_read, 5016, 2, "input")
    local pv_w_primary = 0
    local pv_raw_u32 = 0
    if ok_pv and pv_regs then
        pv_w_primary = host.decode_u32_le(pv_regs[1], pv_regs[2])
        pv_raw_u32   = pv_w_primary
    end

    -- PV MPPT: 5010-5013 (V×0.1, A×0.1 per string)
    local ok_mppt, mppt_regs = pcall(host.modbus_read, 5010, 4, "input")
    local mppt1_v, mppt1_a, mppt2_v, mppt2_a = 0, 0, 0, 0
    if ok_mppt and mppt_regs then
        mppt1_v = mppt_regs[1] * 0.1
        mppt1_a = mppt_regs[2] * 0.1
        mppt2_v = mppt_regs[3] * 0.1
        mppt2_a = mppt_regs[4] * 0.1
    end
    local mppt1_w = mppt1_v * mppt1_a
    local mppt2_w = mppt2_v * mppt2_a
    local pv_w_mppt = mppt1_w + mppt2_w

    -- Resolve PV power with a fallback ladder:
    --   1. Trust 5016-5017 if it reports > 50 W (clearly live).
    --   2. Otherwise use MPPT sum if that reports > 50 W (primary
    --      register stuck / firmware quirk).
    --   3. Zero — panels aren't generating right now.
    -- 50 W threshold filters out noise-floor readings without swallowing
    -- genuine low-light output.
    local pv_w = 0
    local pv_source = "zero"
    if pv_w_primary > 50 then
        pv_w = pv_w_primary
        pv_source = "primary_reg"
    elseif pv_w_mppt > 50 then
        pv_w = pv_w_mppt
        pv_source = "mppt_sum"
    end

    -- PV lifetime energy: 13002-13003, U32 LE × 0.1 kWh
    local ok_pvgen, pvgen_regs = pcall(host.modbus_read, 13002, 2, "input")
    local pv_gen_wh = 0
    if ok_pvgen and pvgen_regs then
        pv_gen_wh = host.decode_u32_le(pvgen_regs[1], pvgen_regs[2]) * 0.1 * 1000
    end

    -- Rated power: 5000, U16 × 0.1 kW
    local ok_rated, rated_regs = pcall(host.modbus_read, 5000, 1, "input")
    local rated_w = rated_ac_w
    if ok_rated and rated_regs then
        rated_w = rated_regs[1] * 0.1 * 1000
        if rated_w > 0 then rated_ac_w = rated_w end
    end

    -- Heatsink temp: 5007, I16 × 0.1 C
    local ok_temp, temp_regs = pcall(host.modbus_read, 5007, 1, "input")
    local heatsink_c = 0
    if ok_temp and temp_regs then
        heatsink_c = host.decode_i16(temp_regs[1]) * 0.1
    end

    -- Grid frequency: 5241, U16 × 0.01 Hz
    local ok_hz, hz_regs = pcall(host.modbus_read, 5241, 1, "input")
    local hz = 0
    if ok_hz and hz_regs then
        hz = hz_regs[1] * 0.01
    end

    host.emit("pv", {
        w           = -pv_w,  -- negative = generation (EMS convention)
        mppt1_v     = mppt1_v,
        mppt1_a     = mppt1_a,
        mppt2_v     = mppt2_v,
        mppt2_a     = mppt2_a,
        mppt1_w     = mppt1_w,
        mppt2_w     = mppt2_w,
        pv_source   = pv_source,  -- "primary_reg" | "mppt_sum" | "zero"
        lifetime_wh = pv_gen_wh,
        rated_w     = rated_w,
        temp_c      = heatsink_c,
    })
    -- Diagnostics: long-format TS DB. Surface BOTH the primary-register
    -- reading and the MPPT-derived fallback so operators can see when
    -- the two disagree (= firmware register quirk) directly in the
    -- metric browser.
    host.emit_metric("pv_w_primary",     pv_w_primary)
    host.emit_metric("pv_w_mppt_sum",    pv_w_mppt)
    host.emit_metric("pv_raw_u32",       pv_raw_u32)
    host.emit_metric("pv_mppt1_v",       mppt1_v)
    host.emit_metric("pv_mppt1_a",       mppt1_a)
    host.emit_metric("pv_mppt1_w",       mppt1_w)
    host.emit_metric("pv_mppt2_v",       mppt2_v)
    host.emit_metric("pv_mppt2_a",       mppt2_a)
    host.emit_metric("pv_mppt2_w",       mppt2_w)
    host.emit_metric("inverter_temp_c",  heatsink_c)
    host.emit_metric("grid_hz",          hz)
    host.emit_metric("sungrow_running_state", running_state)
    host.emit_metric("sungrow_power_flow_status", power_flow_status)
    host.emit_metric("sungrow_pv_curtail_method", pv_curtail_method == "feed_in" and 2 or 1)

    -- Contiguous bitfields from documented input registers 13050-13079
    -- (zero-based host addresses 13049-13078). One read gives enough evidence
    -- to distinguish thermal, grid, PV/DC, battery and BMS shutdowns.
    local ok_faults, fault_regs = pcall(host.modbus_read, 13049, 30, "input")
    local fault_values = {}
    if ok_faults and fault_regs and #fault_regs >= 30 then
        local fault_names = {
            "sungrow_inverter_alarm_bits",
            "sungrow_grid_fault_bits",
            "sungrow_system_fault1_bits",
            "sungrow_system_fault2_bits",
            "sungrow_dc_fault_bits",
            "sungrow_permanent_fault_bits",
            "sungrow_bdc_fault_bits",
            "sungrow_bdc_permanent_fault_bits",
            "sungrow_battery_fault_bits",
            "sungrow_battery_alarm_bits",
            "sungrow_bms_alarm_bits",
            "sungrow_bms_protection_bits",
            "sungrow_bms_fault1_bits",
            "sungrow_bms_fault2_bits",
            "sungrow_bms_alarm2_bits",
        }
        for i, name in ipairs(fault_names) do
            local j = (i - 1) * 2 + 1
            local value = host.decode_u32_le(fault_regs[j], fault_regs[j + 1])
            fault_values[i] = value
            host.emit_metric(name, value)
        end
    end

    -- A faulted inverter can keep returning perfectly fresh Modbus telemetry,
    -- which previously made /api/status and Diagnose say "ok" while PV and
    -- battery actuation were physically unavailable. Surface Sungrow's actual
    -- running state through the host's device-fault channel. RecordSuccess does
    -- not clear this flag; only a later non-fault running-state poll does.
    if running_state == 0x5500 or running_state == 0x0100 then
        local reason = string.format("Sungrow fault (running state 0x%04X)", running_state)
        local system_fault2 = fault_values[4] or 0
        if bit_is_set(system_fault2, 1) then
            reason = string.format(
                "Sungrow fault: excessively high ambient temperature (%.1f C, state 0x%04X)",
                heatsink_c, running_state)
        end
        host.set_device_fault(true, reason)
    elseif ok_running and running_regs and running_regs[1] ~= nil then
        host.set_device_fault(false, "")
    end

    -- Battery: 13019-13022 (voltage, current, power, SoC)
    local ok_bat, bat_regs = pcall(host.modbus_read, 13019, 4, "input")
    local bat_v, bat_a, bat_w, bat_soc = 0, 0, 0, 0
    if ok_bat and bat_regs then
        bat_v   = bat_regs[1] * 0.1
        bat_a   = bat_regs[2] * 0.1
        bat_w   = bat_regs[3]
        bat_soc = bat_regs[4] * 0.1 / 100  -- 0-1 fraction
    end

    -- Apply sign: Sungrow reports power as unsigned, direction from status register
    -- EMS convention: positive = charging, negative = discharging
    if is_discharging then
        bat_w = -bat_w
    end

    -- Battery charge energy: 13040-13041, U32 LE × 0.1 kWh
    local ok_bchg, bchg_regs = pcall(host.modbus_read, 13040, 2, "input")
    local bat_charge_wh = 0
    if ok_bchg and bchg_regs then
        bat_charge_wh = host.decode_u32_le(bchg_regs[1], bchg_regs[2]) * 0.1 * 1000
    end

    -- Battery discharge energy: 13026-13027, U32 LE × 0.1 kWh
    local ok_bdis, bdis_regs = pcall(host.modbus_read, 13026, 2, "input")
    local bat_discharge_wh = 0
    if ok_bdis and bdis_regs then
        bat_discharge_wh = host.decode_u32_le(bdis_regs[1], bdis_regs[2]) * 0.1 * 1000
    end

    host.emit("battery", {
        w            = bat_w,
        v            = bat_v,
        a            = bat_a,
        soc          = bat_soc,
        charge_wh    = bat_charge_wh,
        discharge_wh = bat_discharge_wh,
    })
    host.emit_metric("battery_dc_v", bat_v)
    host.emit_metric("battery_dc_a", bat_a)

    -- EMS state diagnostics — what the inverter *actually* has latched
    -- in its control registers right now. With the #164 write-order fix
    -- these should track whatever the dispatcher sent last tick; any
    -- drift between target and ems_force_w points at external writers
    -- (iSolarCloud, HA integration, another EMS) racing the driver.
    local ok_emsd, emsd = pcall(host.modbus_read, 13049, 3, "holding")
    if ok_emsd and emsd then
        host.emit_metric("sungrow_ems_mode",  emsd[1]) -- 0=self, 2=forced, 3=ext
        host.emit_metric("sungrow_force_cmd", emsd[2]) -- 0xAA=170 chg, 0xBB=187 dis, 0xCC=204 stop
        host.emit_metric("sungrow_force_w",   emsd[3])
    end

    -- Grid meter power: 5600-5601, I32 LE, watts (positive=import, negative=export)
    local ok_mw, mw_regs = pcall(host.modbus_read, 5600, 2, "input")
    local meter_w = 0
    if ok_mw and mw_regs then
        meter_w = host.decode_i32_le(mw_regs[1], mw_regs[2])
    end

    -- Per-phase power: 5602-5607, I32 LE pairs
    local ok_mp, mp_regs = pcall(host.modbus_read, 5602, 6, "input")
    local l1_w, l2_w, l3_w = 0, 0, 0
    if ok_mp and mp_regs then
        l1_w = host.decode_i32_le(mp_regs[1], mp_regs[2])
        l2_w = host.decode_i32_le(mp_regs[3], mp_regs[4])
        l3_w = host.decode_i32_le(mp_regs[5], mp_regs[6])
    end

    -- Per-phase voltage: 5740-5742, U16 × 0.1 V
    local ok_mv, mv_regs = pcall(host.modbus_read, 5740, 3, "input")
    local l1_v, l2_v, l3_v = 0, 0, 0
    if ok_mv and mv_regs then
        l1_v = mv_regs[1] * 0.1
        l2_v = mv_regs[2] * 0.1
        l3_v = mv_regs[3] * 0.1
    end

    -- Per-phase current: 5743-5745, U16 × 0.01 A
    local ok_ma, ma_regs = pcall(host.modbus_read, 5743, 3, "input")
    local l1_a, l2_a, l3_a = 0, 0, 0
    if ok_ma and ma_regs then
        l1_a = ma_regs[1] * 0.01
        l2_a = ma_regs[2] * 0.01
        l3_a = ma_regs[3] * 0.01
    end

    -- Import energy: 13036-13037, U32 LE × 0.1 kWh
    local ok_imp, imp_regs = pcall(host.modbus_read, 13036, 2, "input")
    local import_wh = 0
    if ok_imp and imp_regs then
        import_wh = host.decode_u32_le(imp_regs[1], imp_regs[2]) * 0.1 * 1000
    end

    -- Export energy: 13045-13046, U32 LE × 0.1 kWh
    local ok_exp, exp_regs = pcall(host.modbus_read, 13045, 2, "input")
    local export_wh = 0
    if ok_exp and exp_regs then
        export_wh = host.decode_u32_le(exp_regs[1], exp_regs[2]) * 0.1 * 1000
    end

    host.emit("meter", {
        w         = meter_w,
        l1_w      = l1_w,
        l2_w      = l2_w,
        l3_w      = l3_w,
        l1_v      = l1_v,
        l2_v      = l2_v,
        l3_v      = l3_v,
        l1_a      = l1_a,
        l2_a      = l2_a,
        l3_a      = l3_a,
        hz        = hz,
        import_wh = import_wh,
        export_wh = export_wh,
    })
    host.emit_metric("meter_l1_w", l1_w)
    host.emit_metric("meter_l2_w", l2_w)
    host.emit_metric("meter_l3_w", l3_w)
    host.emit_metric("meter_l1_v", l1_v)
    host.emit_metric("meter_l2_v", l2_v)
    host.emit_metric("meter_l3_v", l3_v)
    host.emit_metric("meter_l1_a", l1_a)
    host.emit_metric("meter_l2_a", l2_a)
    host.emit_metric("meter_l3_a", l3_a)

    -- Feed-in fallback translation: a PV allowance is the power that may
    -- serve local load, charge the battery, or leave the site. Sungrow's
    -- legacy SHxRT register controls only the last term, so subtract current
    -- non-export absorption. This preserves useful self-consumption while
    -- preventing paid/negative-price export. A manual cap below live local
    -- absorption cannot force DC PV lower on this firmware; it safely floors
    -- the export allowance at zero instead.
    local load_w = meter_w - bat_w + pv_w
    latest_non_export_w = math.max(0, load_w + math.max(0, bat_w))

    return 5000
end

function driver_command(action, value, context)
    return nil, "Sungrow observe-only target has no commands"
end

function driver_default_mode()
    return nil
end

function driver_cleanup()
end
