name: "hello"
version: "1.1.0"
tier: community
author: ""
protocol: ""
ders: [meter]
control: false
tested_devices: []
min_host_version: "2.0.0"
size_bytes: 1337
dkb_id: ""
sha256: "da7d2e6512086f0268a5fdd66610dbdc41877c98ea49484e8036146e821eeaee"
signature: ""

bytecode_sha256: ""
bytecode_signature: ""
bytecode_size: 0
changelog: ""
