name: "hello"
version: "1.1.0"
tier: community
author: ""
protocol: ""
ders: [meter]
control: false
tested_devices: []
min_host_version: "2.0.0"
size_bytes: 1362
dkb_id: ""
sha256: "6e4bb97258f27ff940366454bd7600f801f5f24a332ec792f80dc0c332fd56e0"
signature: ""

bytecode_sha256: ""
bytecode_signature: ""
bytecode_size: 0
changelog: ""
