#!/usr/bin/env python3
"""Derive the Sungrow observe-only target from the exact FTW baseline."""

from __future__ import annotations

import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BASELINE = ROOT / "baselines" / "ftw" / "drivers" / "sungrow.lua"
TARGET = ROOT / "packages" / "v1" / "sungrow" / "targets" / "ftw-observe.lua"
BASELINE_SHA256 = "466a5f8637e6756fc2e1af4197d4edc1845474231413c0016f0e5900acb7b7ac"


def extract(source: str, start: str, end: str) -> str:
    start_at = source.index(start)
    end_at = source.index(end, start_at)
    return source[start_at:end_at].rstrip()


def main() -> int:
    source_bytes = BASELINE.read_bytes()
    digest = hashlib.sha256(source_bytes).hexdigest()
    if digest != BASELINE_SHA256:
        raise SystemExit(f"FTW Sungrow baseline hash differs: {digest}")

    source = source_bytes.decode("utf-8")
    fingerprint = extract(
        source,
        "function driver_fingerprint()",
        "\n----------------------------------------------------------------------------\n-- Initialization",
    )
    poll = extract(
        source,
        "function driver_poll()",
        "\n----------------------------------------------------------------------------\n-- Battery control",
    )
    target = f'''-- Generated by tools/derive_sungrow_ftw_observe.py.
-- Source: srcfl/ftw@699873db3e7abe81f76e8110d1cefa4a38ba6efb
-- Path: drivers/sungrow.lua
-- SHA-256: {BASELINE_SHA256}
-- The fingerprint and poll functions stay byte-for-byte equal to the FTW
-- legacy source. Init and lifecycle code remove every write path.

DRIVER = {{
  host_api_min = 1,
  host_api_max = 1,
  id           = "sungrow",
  name         = "Sungrow observe-only pilot",
  manufacturer = "Sungrow",
  version      = "1.3.2",
  legacy_ids   = {{ "sungrow-shx" }},
  protocols    = {{ "modbus" }},
  capabilities = {{ "meter", "pv", "battery" }},
  description  = "Sungrow SH-series telemetry via Modbus TCP.",
  homepage     = "https://en.sungrowpower.com",
  authors      = {{ "FTW contributors" }},
  tested_models = {{ "SH5.0RT", "SH6.0RT", "SH8.0RT", "SH10RT" }},
  verification_status = "experimental",
  verification_notes = "Observe only. Exact pilot model and firmware approval is required.",
  connection_defaults = {{
    port    = 502,
    unit_id = 1,
  }},
}}

PROTOCOL = "modbus"

local APPROVED_MODEL_FIRMWARE_PROFILES = {{}}
local sn_read = false
local rated_ac_w = 0
local pv_curtail_method = "active_power"
local latest_non_export_w = 0

local function bit_is_set(value, bit)
    return math.floor(value / (2 ^ bit)) % 2 == 1
end

{fingerprint}

function driver_init(config)
    config = config or {{}}
    local model = tostring(config.model or "")
    local firmware = tostring(config.firmware or "")
    if not APPROVED_MODEL_FIRMWARE_PROFILES[model .. "|" .. firmware] then
        error(
            "Sungrow observe-only profile is not approved for model '" ..
            model .. "' and firmware '" .. firmware .. "'"
        )
    end

    host.set_make("Sungrow")
    local ok, dev = pcall(host.modbus_read, 4999, 1, "input")
    if ok and dev then
        host.log("info", "Device type code: " .. tostring(dev[1]))
    end
    local ok_rated, rated = pcall(host.modbus_read, 5000, 1, "input")
    if ok_rated and rated and rated[1] and rated[1] > 0 then
        rated_ac_w = rated[1] * 0.1 * 1000
    end
    local ok_ems, ems = pcall(host.modbus_read, 13049, 3, "holding")
    if ok_ems and ems then
        host.log("info", "EMS state: mode=" .. tostring(ems[1])
            .. " cmd=0x" .. string.format("%04x", ems[2])
            .. " power=" .. tostring(ems[3]) .. "W")
    end
end

{poll}

function driver_command(action, value, context)
    return nil, "Sungrow observe-only target has no commands"
end

function driver_default_mode()
    return nil
end

function driver_cleanup()
end
'''
    TARGET.write_text(target, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} from FTW baseline {digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
